# Generated by Django 3.0 on 2019-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportgroupconductor',
            name='conducts',
            field=models.ManyToManyField(null=True, to='main.SupportGroup'),
        ),
    ]
