# Generated by Django 3.0 on 2019-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191218_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='name',
            field=models.CharField(default='Support Group Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='conducted_by',
            field=models.ManyToManyField(to='main.SupportGroupConductor'),
        ),
    ]
