# Generated by Django 3.0 on 2019-12-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191217_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='helpingstaff',
            name='role',
            field=models.CharField(choices=[('ws', 'Ward Staff'), ('ls', 'Lab Staff'), ('n', 'None')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
