# Generated by Django 3.0 on 2019-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191218_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportgroup',
            name='participants',
        ),
    ]
