# Generated by Django 3.0 on 2019-12-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191217_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.PositiveIntegerField(default=0)),
                ('timing', models.TimeField()),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='labappointment',
            name='lab',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labappointment',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.HelpingStaff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Lab_appointments',
            field=models.ManyToManyField(through='main.LabAppointment', to='main.HelpingStaff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_appointments',
            field=models.ManyToManyField(through='main.DoctorAppointment', to='main.Doctor'),
        ),
        migrations.CreateModel(
            name='SupportGroupConductor',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Staff')),
                ('conducts', models.ManyToManyField(through='main.SupportGroup', to='main.Patient')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('main.staff',),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='support_group_conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SupportGroupConductor'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.DoctorAppointment')),
                ('tests', models.ManyToManyField(to='main.LabTest')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LabAppointment')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DoctorAppointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('discharged', models.BooleanField(default=False)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HelpingStaff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ward')),
            ],
        ),
        migrations.AddField(
            model_name='labappointment',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Prescription'),
        ),
    ]
