# Generated by Django 3.0 on 2019-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_supportgroup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
