# Generated by Django 3.0 on 2019-12-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191217_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admissions',
            new_name='Admission',
        ),
        migrations.AddField(
            model_name='bill',
            name='addmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Admission'),
        ),
        migrations.AddField(
            model_name='bill',
            name='lab_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LabAppointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DoctorAppointment'),
        ),
    ]
