# Generated by Django 3.0 on 2019-12-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191217_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Admission'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='doctorappointment',
            options={'verbose_name': 'Doctor Appointment'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'Drug'},
        ),
        migrations.AlterModelOptions(
            name='helpingstaff',
            options={'verbose_name': 'Helping Staff'},
        ),
        migrations.AlterModelOptions(
            name='labappointment',
            options={'verbose_name': 'Lab Appointment'},
        ),
        migrations.AlterModelOptions(
            name='labreport',
            options={'verbose_name': 'Lab Report'},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'verbose_name': 'Lab Test'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescription'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'verbose_name': 'Support Group'},
        ),
        migrations.AlterModelOptions(
            name='supportgroupconductor',
            options={'verbose_name': 'Support Group Conductor'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'verbose_name': 'Patient'},
        ),
    ]
