# Generated by Django 3.0 on 2019-12-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191218_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='fee',
        ),
    ]
