# Generated by Django 3.0.1 on 2020-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_doctorappointment_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='price',
            new_name='fee',
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
