# Generated by Django 3.0.1 on 2020-01-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_labappointment_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportgroup',
            name='conducted_by',
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SupportGroupConductor'),
        ),
    ]
