# Generated by Django 3.0 on 2019-12-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
